### PR TITLE
Update db tables  create date and last changed date attribute

### PR DESCRIPTION
**Pull request by jjeroch**
@ntruchsess  & @wira-mms 
As discussed, I started to update / delete "date_created" attributes as well as "date_last_changed"

Additionally I have added the static data for the "use_cases" table.

@wira-mms : app table has now the field "provider"

### CODE REVIEW

**Review by wira-mms — CHANGES_REQUESTED** [review]
Please remove .DS_Store, it's from your MacOS file system and doesn't belong to the project

**Review by wira-mms — CHANGES_REQUESTED** [review]
Please also review added/removed data in 22-portal-content.sql 😬

**Comment by jjeroch** [comment]
@wira-mms 
DS_Store cant get removed, we can only push it into the gitignore. Not sure if that was successfully. Please have a quick look

About the file 22 - I havn't touched file 22. Do you mean the country table? Not touched, but I saw that a row was added 1:1 the same as it was before. Not sure why, but from my point of view thats not an issue

**Comment by wira-mms** [comment]
> @wira-mms DS_Store cant get removed, we can only push it into the gitignore. Not sure if that was successfully. Please have a quick look
> 
> About the file 22 - I havn't touched file 22. Do you mean the country table? Not touched, but I saw that a row was added 1:1 the same as it was before. Not sure why, but from my point of view thats not an issue

Hmm, it's still checked in. Let me see if I can remove it.

**Review by wira-mms — APPROVED** [review]

**Pull request merged**
